# Generated by Django 5.2.6 on 2025-10-01 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Player',
        ),
        migrations.RenameField(
            model_name='attempt',
            old_name='user',
            new_name='player',
        ),
    ]
