# Generated by Django 5.2.6 on 2025-10-01 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0002_rename_user_player_rename_user_attempt_player'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='level',
            name='level_number',
        ),
        migrations.AddField(
            model_name='attempt',
            name='answer',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='level',
            name='level_identifier',
            field=models.CharField(max_length=7, null=True),
        ),
    ]
