# Generated by Django 5.2.6 on 2025-10-01 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0003_remove_level_level_number_attempt_answer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='level',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
