# Generated by Django 5.2.6 on 2025-10-01 12:19

import play.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0004_level_image_alter_level_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='image',
            field=models.ImageField(null=True, upload_to=play.models.upload_path),
        ),
    ]
