# Generated by Django 5.2.6 on 2025-10-03 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0006_player_last_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='AlignmentV',
            field=models.CharField(choices=[('top', 'Top'), ('center', 'Center'), ('bottom', 'Bottom')], default='center', max_length=10),
        ),
        migrations.AddField(
            model_name='level',
            name='alignH',
            field=models.CharField(choices=[('left', 'Left'), ('center', 'Center'), ('right', 'Right')], default='center', max_length=10),
        ),
    ]
