# Generated by Django 5.2.6 on 2025-10-03 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0008_remove_level_alignmentv_level_alignv_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='alignH',
            field=models.CharField(choices=[('left', 'Left'), ('hcenter', 'Center'), ('right', 'Right')], default='hcenter', max_length=7),
        ),
        migrations.AlterField(
            model_name='level',
            name='alignV',
            field=models.CharField(choices=[('top', 'Top'), ('vcenter', 'Center'), ('bottom', 'Bottom')], default='vcenter', max_length=7),
        ),
    ]
