# Generated by Django 5.2.6 on 2025-10-07 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0010_level_prev_level_level_sourcehint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='sourcehint',
            field=models.TextField(blank=True, null=True),
        ),
    ]
