# Generated by Django 5.2.6 on 2025-10-07 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0011_alter_level_sourcehint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='question',
            field=models.TextField(),
        ),
    ]
