# Generated by Django 5.2.6 on 2025-10-07 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0012_alter_level_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='headcomment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
