# Generated by Django 5.2.6 on 2025-10-09 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0013_level_headcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='routes',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
