# Generated by Django 5.2.6 on 2025-10-03 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0005_alter_level_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='last_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='play.level'),
        ),
    ]
