# Generated by Django 5.2.6 on 2025-10-03 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0007_level_alignmentv_level_alignh'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='level',
            name='AlignmentV',
        ),
        migrations.AddField(
            model_name='level',
            name='alignV',
            field=models.CharField(choices=[('top', 'Top'), ('center', 'Center'), ('bottom', 'Bottom')], default='center', max_length=6),
        ),
        migrations.AlterField(
            model_name='level',
            name='alignH',
            field=models.CharField(choices=[('left', 'Left'), ('center', 'Center'), ('right', 'Right')], default='center', max_length=6),
        ),
    ]
