# Generated by Django 5.2.6 on 2025-10-07 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0009_alter_level_alignh_alter_level_alignv'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='prev_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='play.level'),
        ),
        migrations.AddField(
            model_name='level',
            name='sourcehint',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
