# Generated by Django 5.2.6 on 2026-02-17 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0014_level_routes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('slug', models.SlugField(unique=True)),
                ('content', models.TextField()),
            ],
        ),
    ]
