# Generated by Django 5.2.6 on 2026-02-17 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0015_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='description',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='keywords',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
